dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "racodond"

env:
  global:
  - secure: "BlP+1c61fS6hpPXhVRXzSr5oKc91wHJqoW+Zs8A1EBzDvAVg5AQ1EwhYcpfPT848olCaM4zw0cUc2B1aRZPQXYaOwaejI0dYOTm9yShkzK1fCTAzCVyGcuDZJ3jli0vjpiSGL/XWXMi6y9j59TxzwngPdaDazWFZ0V15geP1Z/P7rXv/iFVEdcWe5iryE0K9LmLWD7R26mD8PY6OnE+IeFt0b+9a63Je8Ufx8dYpnJK/ioD4s2hDgxMpO+9g/pMkCIsvFvZsBGaAS4ZPzCVP1B6mrCFCOvlIUV281qd7m4bZAf2qCjP5e3ckLLhVxaJfZ3bZk1Fbps0b1WmF4ioHGpYWTKkuVnRgjgsUX2sBVZinTZQkU2aXqxYIrri2MJaK1iSZy/9pZK+Gw/kR3Psxw0GmdaMxQc6ovZlVemQLpRk032zAbSvmxAS1SWV46maVTnYSNtiDGO1owoZh1iV6G1cDBYkodjGDaVdM1db5tuh6nb6NjJcIxbbfbL72dOEtZY/ms1ByQnI3yFAAcLobi7ZK/Mh6QgDDC+F8BD4TnCRl8PdeDkGT845y78KWEoDEC9b3J+ZDC1YDiV/1p/S44G+rJQtEvgzSnJnLR2MwNoUic9y7OWyimf+vvFihHFlsjTFi2+tkOCdKZ+iTcUfJ98Q8yPrEWEDjinUM8dC47sQ="
  - secure: "JhRWOcneReq5QzfeXc8KShbxuv3cUX1El1f+fvrrxvD3fRjMe2ASBN2M04GPcJ66bXwEqLUy6sC3pPC/Kav1XBpRU6uxes716LQnEe3vDBQV04vF8zpdK8Pf2bEnNPJrmANlokfIWVVcTl3LLMZl66L3sHJej/vjdl+jKT7XHN0TGC2kwrX2iNwYJNslHWErF0K6H9bw6S6K+thHyy3Hd7WSZbFDdIUdisOZ3KrlsR/zmXuvCtYmYfQJDATFFeL2xWXpe3VhCcYpGshzqxc9pFzBBLdehlcC2RkGNt7iiHxn870fjgrmzTp4djY6ra+5ySPH7N+V2R8xEQAa+Ijdt1h6KYPWus35RZ7ST9mqTLaatliexz8dlV9BYBnCO8Vt/Nbp1ruAiZFqHT17SZdzNK02WIIwFS5jvZhl0fg+sdvBqQEWNrCtLoTKQhLXb/BhqUcM4qELa3NcsxCA5Mx+Z1h5i1E+xIAPkc06RuPEf74Ey0P9H4qgauoRISG6Cl0inf1ZuRFDXouAyRp7cYjKN9KjaxEGdmDWzkJigEfCNVU1mcrDq8GfYUteYyFpypeT8nYAf3mwU7QpNc4CT/5MqZRUJmkdGtnXI1ImY7VTXCVaMva9atQNc0P6fxrOR33+BUbBpcvhijWv9Iy+nuqfLX6sd+/723YUCsGw7EoHBrs="

language: node_js
node_js:
  - '8'

jdk:
  - oraclejdk8

cache:
  directories:
    - "$HOME/.sonar/cache"

script: "./travis.sh"
